// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

using Core.Client.Models;

#nullable enable annotations

namespace Core.Client.Services
{
    /// <summary>Current application Manifest</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.4.0.0")]
    public partial interface IManifestApi
    {
        /// <summary>Current application Manifest</summary>
        /// <remarks>Fetches the current application manifest</remarks>
        /// <returns>Result when the application manifest has been retrieved, the body will contain the current application manifest</returns>
        /// <exception cref="ApiException">Thrown when the request returns a non-success status code.</exception>
        [Headers("Accept: application/json")]
        [Get("/manifest")]
        Task<IDictionary<string, ManifestDefinitionDto>> GetAsync();
    }

}