service: core-ruby
frameworkVersion: '4'

provider:
  name: aws
  runtime: ruby2.7

plugins:
  - serverless-offline

functions:
  current_time:
    handler: functions/manifest.endpoint
    events:
      - httpApi:
          path: /time
          method: get
